---
- name: Ping Hosts Playbook
  hosts: all
  gather_facts: no
  tasks:

  - name: Check if the server is online
    ansible.windows.win_ping:
    register: ping_result

  - name: Print the ping result
    debug:
      var: ping_result

  - name: Copy Script 1 to the host
    ansible.windows.win_copy:
      src: ./Script.ps1
      dest: C:\Temp\Script.ps1
    when: ping_result.ping == "pong"

  - name: Copy Script 2 to the host
    ansible.windows.win_copy:
      src: ./GetHCIAKSconfig.ps1
      dest: C:\Temp\GetHCIAKSconfig.ps1
    when: ping_result.ping == "pong"
  
  - name: Get the list of updates for the StackHCI
    ansible.windows.win_shell: "powershell C:\\Temp\\Script.ps1 -username {{ username }} -password {{ password }}"
    when: ping_result.ping == "pong"

  - name: Get configuration for the StackHCI
    ansible.windows.win_shell: "powershell C:\\Temp\\GetHCIAKSconfig.ps1 -username {{ username }} -password {{ password }}"
    when: ping_result.ping == "pong"

  - name: Read updates status
    ansible.windows.win_shell: 'type C:\\Temp\\updateresult.txt'  
    register: updates_status
    when: ping_result.ping == "pong"

  - name: Read configuration status
    ansible.windows.win_shell: 'type C:\\Temp\\configresult.txt'  
    register: config_status
    when: ping_result.ping == "pong"

  - name: Print the updates status
    debug:
      var: updates_status.stdout_lines
  
  - name: Print the configuration status
    debug:
      var: config_status.stdout_lines

  - name: Remove a file, if present
    ansible.windows.win_file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "C:\\Temp\\configresult.txt"
      - "C:\\Temp\\updateresult.txt"
      - "C:\\Temp\\Script.ps1"
      - "C:\\Temp\\GetHCIAKSconfig.ps1"
    when: ping_result.ping == "pong"