---
- name: Ping Hosts Playbook
  hosts: all
  gather_facts: no
  tasks:

  - name: Check if the server is online
    ansible.windows.win_ping:
    register: ping_result

  - name: Print the ping result
    debug:
      var: ping_result
  
  - name: Get the list of updates for the StackHCI
    script: "./Script.ps1 -username {{ username }} -password {{ password }}"
    when: ping_result.ping == "pong"
    register: updates
  
  - name: Print the updates
    debug:
      var: updates
    when: updates.stdout != ""

  - name: Overwrite update status
    debug:
      msg: "Updates are not available"
    when: updates.stdout = ""