---
- name: Ping Hosts Playbook
  hosts: all
  gather_facts: no
  tasks:

  - name: Check if the server is online
    ansible.windows.win_ping:
    register: ping_result

  - name: Print the ping result
    debug:
      var: ping_result

  - name: Copy Script 1 to the host
    ansible.windows.win_copy:
      src: ./Script.ps1
      dest: C:\Temp\Script.ps1
    when: ping_result.ping == "pong"

  - name: Copy Script 2 to the host
    ansible.windows.win_copy:
      src: ./GetHCIAKSconfig.ps1
      dest: C:\Temp\GetHCIAKSconfig.ps1
    when: ping_result.ping == "pong"
  
  - name: Get the list of updates for the StackHCI
    ansible.windows.win_shell: "powershell C:\\Temp\\Script.ps1 -username {{ username }} -password {{ password }}"
    when: ping_result.ping == "pong"
    register: updates
  
  - name: Print the updates
    debug:
      var: updates
    when: updates.stdout != ""

  - name: Overwrite update status
    debug:
      msg: "Updates are not available"
    when: updates.stdout == ""

  - name: Get configuration for the StackHCI
    ansible.windows.win_shell: "powershell C:\\Temp\\GetHCIAKSconfig.ps1 -username {{ username }} -password {{ password }}"
    when: ping_result.ping == "pong"
    register: config

  - name: Print the AKS configurations of Stack HCI hosts
    debug:
      var: config
    when: config.stdout != ""