---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    user: 'tommasosacco.1991@outlook.it'
    passwd: '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'
  tasks:

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefixes: "{{ address_prefixes }}"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefix: "{{ address_prefix }}"
      virtual_network: "{{ vm_name }}"
  - name: Create HostPool
    azure_rm_deployment:
      resource_group: "{{ resource_group }}"
      location: "{{ location }}"
      name: myDeployment
      template_link: 'https://074fee220b09d52c5b4b495d808c308044c33cc1@raw.githubusercontent.com/DevOpsStyle/DeployTest/main/template.json'
      parameters_link: 'https://074fee220b09d52c5b4b495d808c308044c33cc1@raw.githubusercontent.com/DevOpsStyle/DeployTest/main/parameters.json'