---
- name: Create Azure VM
  hosts: localhost
  connection: local
  vars:
    resource_group: "AzureAnsibleAVD"
    vm_name: WVD
    location: westeurope
  tasks:

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ vm_name }}"
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      virtual_network: "{{ vm_name }}"
      subnet: "{{ vm_name }}"
      public_ip_name: "{{ vm_name }}"
      security_group: "{{ vm_name }}"  
  - name: Create HostPool
    shell: az desktopvirtualization hostpool create --name "MyHostPool" --resource-group "VirtualDesktop" --location "westeurope" --host-pool-type "Pooled" --load-balancer-type "BreadthFirst" --max-session-limit 10 --personal-desktop-assignment-type "Automatic"  --registration-info expiration-time="2022-03-22T14:01:54.9571247Z" registration-token-operation="Update" --sso-context "KeyVaultPath" --description "Description of this host pool" --friendly-name "Friendly name of this host pool"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      vm_size: Standard B2s
      admin_username: Sergio
      admin_password: Sergiotest123@
      network_interfaces: "{{ vm_name }}"
      image:
        offer: Windows-10
        publisher: MicrosoftWindowsDesktop
        sku: 19h2-evd-g2
        version: latest
