---
- name: Deploy New Azure Resource Group Playbook
  hosts: localhost
  gather_facts: False
  tasks:

  - name: Creating Resource Group
    azure_rm_resourcegroup:
      name: "{{ resourcegroupname }}"
      location: "{{ resourcegrouplocation }}" 
    