---
- name: Deploy New Azure Resource Group Playbook
  hosts: localhost
  gather_facts: False
  tasks:

  - name: Creating Resource Group
    azure_rm_resourcegroup:
      name: AnsibleIaaS
      location: westeurope
    vars:
      client_id: "{{ client_id }}"
      secret: "{{ secret }}"
      subscription_id: "{{ subscription_id }}"
      tenant: "{{ tenant }}"
#TESTING
    